# Auto-generated: 2025-10-06T09:16:58+13:00
set -euo pipefail
mkdir -p 'gqdp'
# Whole-population SNP-only GQ>=30 & DP 10..200
# Generated by wholepop_snps_gq30_dp10_200.sh
if [[ ! -s 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.gqge30.dp10_200.nomisssites.bcf' ]]; then
  bcftools filter --threads 48 -S . -e 'FMT/GQ<30 || FMT/DP<10 || FMT/DP>200' --set-GTs . 'merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.bcf' -Ou | bcftools +fill-tags -Ou -- -t AN | bcftools view --threads 48 -e 'INFO/AN=0' -O b -o 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.gqge30.dp10_200.nomisssites.bcf' && bcftools index -f 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.gqge30.dp10_200.nomisssites.bcf'
else
  echo "[skip] exists: gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.gqge30.dp10_200.nomisssites.bcf" 1>&2
fi
if [[ ! -s 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.gqge30.dp10_200.nomisssites.bcf' ]]; then
  bcftools filter --threads 48 -S . -e 'FMT/GQ<30 || FMT/DP<10 || FMT/DP>200' --set-GTs . 'merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.bcf' -Ou | bcftools +fill-tags -Ou -- -t AN | bcftools view --threads 48 -e 'INFO/AN=0' -O b -o 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.gqge30.dp10_200.nomisssites.bcf' && bcftools index -f 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.gqge30.dp10_200.nomisssites.bcf'
else
  echo "[skip] exists: gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.gqge30.dp10_200.nomisssites.bcf" 1>&2
fi
if [[ ! -s 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.fmissing_le0.2.gqge30.dp10_200.nomisssites.bcf' ]]; then
  bcftools filter --threads 48 -S . -e 'FMT/GQ<30 || FMT/DP<10 || FMT/DP>200' --set-GTs . 'merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.fmissing_le0.2.bcf' -Ou | bcftools +fill-tags -Ou -- -t AN | bcftools view --threads 48 -e 'INFO/AN=0' -O b -o 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.fmissing_le0.2.gqge30.dp10_200.nomisssites.bcf' && bcftools index -f 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.fmissing_le0.2.gqge30.dp10_200.nomisssites.bcf'
else
  echo "[skip] exists: gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.fmissing_le0.2.gqge30.dp10_200.nomisssites.bcf" 1>&2
fi
if [[ ! -s 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.fmissing_le0.2.macge2.gqge30.dp10_200.nomisssites.bcf' ]]; then
  bcftools filter --threads 48 -S . -e 'FMT/GQ<30 || FMT/DP<10 || FMT/DP>200' --set-GTs . 'merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.fmissing_le0.2.macge2.bcf' -Ou | bcftools +fill-tags -Ou -- -t AN | bcftools view --threads 48 -e 'INFO/AN=0' -O b -o 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.fmissing_le0.2.macge2.gqge30.dp10_200.nomisssites.bcf' && bcftools index -f 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.fmissing_le0.2.macge2.gqge30.dp10_200.nomisssites.bcf'
else
  echo "[skip] exists: gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.qualge20.fmissing_le0.2.macge2.gqge30.dp10_200.nomisssites.bcf" 1>&2
fi
