# Auto-generated: 2025-10-06T10:52:40+13:00
set -euo pipefail
mkdir -p 'gqdp'
mkdir -p 'gqdp/step1'
# Single-target SNP-only GQ>=25 & DP 5..200 then F_MISSING<=0.5 and MAC>=2
# Generated by single_snps_gq25_dp5_200_miss0.5_mac2.sh
if [[ ! -s 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.gqge25.dp5_200.fmissle0.5.macge2.bcf' ]]; then
  bcftools filter --threads 48 -S . -e 'FMT/GQ<25 || FMT/DP<5 || FMT/DP>200' --set-GTs . 'merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.bcf' -Ob -o 'gqdp/step1/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.gqge25.dp5_200.nulled.bcf'
  bcftools +fill-tags 'gqdp/step1/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.gqge25.dp5_200.nulled.bcf' -Ou -- -t AN,AC,MAF | bcftools view --threads 48 -e 'F_MISSING > 0.5 || ( MAC < 2 && ( INFO/MAF*INFO/AN ) < 2 )' -Ob -o 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.gqge25.dp5_200.fmissle0.5.macge2.bcf' && bcftools index -f 'gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.gqge25.dp5_200.fmissle0.5.macge2.bcf'
  : = true
else
  echo "[skip] exists: gqdp/merged.a9.unfiltered.2025-09-08.removed_samples.snps_biallelic.gqge25.dp5_200.fmissle0.5.macge2.bcf" 1>&2
fi
