#!/usr/bin/env bash
set -euo pipefail

# Whole-population MAF>=0.05 filter command builder and optional runner
# - Discovers .bcf files in the current directory
# - Skips files that appear already MAF-filtered (name contains 'mafge')
# - By default, skips split-by-population files (name contains '.split_') to ensure WHOLE-POP MAF
# - Produces a runnable script with explicit bcftools commands and a log of those commands
# - Does NOT execute bcftools by default (dry-run); use --run to execute

MAF_THRESHOLD="0.05"
OUTDIR="maf0.05"
RUN=0
INCLUDE_SPLIT=0
FORCE=0
RUN_SCRIPT="run_wholepop_maf0.05.sh"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOGFILE="maf_filter_commands_${TIMESTAMP}.log"

usage() {
  cat <<EOF
Usage: $(basename "$0") [--run] [--outdir DIR] [--include-split] [--force]

Builds bcftools command lines to apply whole-population MAF>=${MAF_THRESHOLD} to BCFs in the current folder.

Options:
  --run             Execute the generated commands (default: dry-run only)
  --outdir DIR      Output directory for filtered BCFs (default: ${OUTDIR})
  --include-split   Include files with '.split_' in their name (not whole-pop)
  --force           Overwrite existing outputs
  -h, --help        Show this help

Artifacts:
  - ${RUN_SCRIPT}         Runnable script with explicit bcftools commands
  - ${LOGFILE}            Log of commands (also printed to stdout)

Notes:
  - Commands compute INFO/MAF with bcftools +fill-tags, then filter on INFO/MAF>=${MAF_THRESHOLD}.
  - Requires bcftools with the +fill-tags plugin available in PATH.
EOF
}

while [[ ${#} -gt 0 ]]; do
  case "$1" in
    --run) RUN=1; shift ;;
    --outdir) OUTDIR="$2"; shift 2 ;;
    --include-split) INCLUDE_SPLIT=1; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

mkdir -p "${OUTDIR}"
echo "# Auto-generated: $(date -Is)" > "${RUN_SCRIPT}"
echo "set -euo pipefail" >> "${RUN_SCRIPT}"
echo "mkdir -p '${OUTDIR}'" >> "${RUN_SCRIPT}"
echo "# Whole-population MAF >= ${MAF_THRESHOLD}" >> "${RUN_SCRIPT}"
echo "# Generated by $(basename "$0")" >> "${RUN_SCRIPT}"

touch "${LOGFILE}"

# Find candidate BCFs (current directory only)
mapfile -t bcfs < <(find . -maxdepth 1 -type f -name '*.bcf' -printf '%f\n' | sort)

count_total=0
count_skipped_split=0
count_skipped_mafge=0
count_ready=0

for bcf in "${bcfs[@]}"; do
  ((count_total++)) || true

  # Skip already MAF-filtered files by name
  if [[ "${bcf}" == *mafge* ]]; then
    ((count_skipped_mafge++)) || true
    continue
  fi

  # Skip split-by-pop files unless requested
  if [[ ${INCLUDE_SPLIT} -eq 0 && "${bcf}" == *.split_* ]]; then
    ((count_skipped_split++)) || true
    continue
  fi

  base="${bcf%.bcf}"
  out="${OUTDIR}/${base}.mafge${MAF_THRESHOLD}.bcf"

  # Compose the full command (compute MAF tags, filter, index)
  cmd="bcftools +fill-tags '${bcf}' -Ou -- -t MAF | bcftools view -i 'INFO/MAF>=${MAF_THRESHOLD}' -Ob -o '${out}' && bcftools index -f '${out}'"

  # Append to run script with existence/overwrite guard
  if [[ ${FORCE} -eq 1 ]]; then
    echo "${cmd}" >> "${RUN_SCRIPT}"
  else
    cat >> "${RUN_SCRIPT}" <<EOS
if [[ ! -s '${out}' ]]; then
  ${cmd}
else
  echo "[skip] exists: ${out}" 1>&2
fi
EOS
  fi

  # Log and optionally execute
  echo "${cmd}" | tee -a "${LOGFILE}"
  ((count_ready++)) || true
  if [[ ${RUN} -eq 1 ]]; then
    if [[ ${FORCE} -eq 1 || ! -s "${out}" ]]; then
      eval "${cmd}"
    else
      echo "[run-skip] exists: ${out}" 1>&2
    fi
  fi
done

chmod +x "${RUN_SCRIPT}"

echo "" | tee -a "${LOGFILE}"
echo "Summary: total=${count_total} ready=${count_ready} skipped_split=${count_skipped_split} skipped_maf_named=${count_skipped_mafge}" | tee -a "${LOGFILE}"
echo "Created: ${RUN_SCRIPT}" | tee -a "${LOGFILE}"
echo "Log: ${LOGFILE}" | tee -a "${LOGFILE}"

if [[ ${RUN} -eq 1 ]]; then
  echo "Execution finished."
else
  echo "Dry-run complete. Commands logged without execution." | tee -a "${LOGFILE}"
fi

